spring.application.name=expense-api-devinuser17
server.port=8080
app.version=1.0.0
management.endpoints.web.exposure.exclude=metrics

spring.datasource.url=jdbc:h2:mem:expensesdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
