spring.application.name=products-api-devinuser12
server.port=8080

spring.datasource.url=jdbc:h2:mem:productsdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
